define(function(require, exports, module){
	
	var COOKIE_COMMODITY_ID = "ebt-pm-commodity-id",
		COOKIE_COMMODITY_POINT = "ebt-pm-commodity-point",
		COOKIE_COMMODITY_EXCHANGE_SUM = "ebt-pm-commodity-exchange-sum",
		COOKIE_COMMODITY_PRICE = "ebt-pm-commodity-price",
		COOKIE_COMMODITY_THUMBNAIL = "ebt-pm-commodity-thumbnail",
		COOKIE_COMMODITY_NAME = "ebt-pm-commodity-name",
		COOKIE_COMMODITY_QRCODE = "ebt-pm-commodity-qrcode";

	return {
		COOKIE_COMMODITY_ID : COOKIE_COMMODITY_ID,
		COOKIE_COMMODITY_POINT : COOKIE_COMMODITY_POINT,
		COOKIE_COMMODITY_EXCHANGE_SUM : COOKIE_COMMODITY_EXCHANGE_SUM,
		COOKIE_COMMODITY_PRICE : COOKIE_COMMODITY_PRICE,
		COOKIE_COMMODITY_THUMBNAIL : COOKIE_COMMODITY_THUMBNAIL,
		COOKIE_COMMODITY_NAME : COOKIE_COMMODITY_NAME,
		COOKIE_COMMODITY_QRCODE : COOKIE_COMMODITY_QRCODE
	}
});